
# This file controls the behavior of the Supabase CLI.

project_id = "utgpvfczmehjcljfcqvz"

[functions.get-user-by-email]
verify_jwt = true

[functions.update-user-metadata]
verify_jwt = true

[functions.update_user_metadata]
verify_jwt = true

[functions.init-user-settings]
verify_jwt = false
