// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utgpvfczmehjcljfcqvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0Z3B2ZmN6bWVoamNsamZjcXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDAxNzgsImV4cCI6MjA2MDQxNjE3OH0.TgZRQgks0dtVct226t3Ggq2y6irCVv990DLniST44v8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);